sudo: false
language: sourcepawn

addons:
  apt_packages:
    - lib32stdc++6

matrix:
  allow_failures:
    - env: SOURCEMOD=1.10

env:
  - SOURCEMOD=1.10

before_script:
  - wget "https://www.sourcemod.net/latest.php?version=$SOURCEMOD&os=linux" -O sourcemod-$SOURCEMOD-linux.tar.gz
  - tar -xzf sourcemod-$SOURCEMOD-linux.tar.gz
  - cd addons/sourcemod/scripting/
  - mkdir compiled compiled/swarm
  - chmod +x spcomp

script:
  - ./compile.sh zs_*.sp
  - ./compile.sh zombieswarm*.sp
  - ./compile.sh unlock_*.sp
  - ./compile.sh gum*.sp  
  - ./compile.sh grenade_effects.sp
  - ./compile.sh prestige.sp
  - ./compile.sh map_missions.sp